# Generated by Django 5.1.3 on 2025-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="capa",
            field=models.ImageField(blank=True, null=True, upload_to="albuns_capas/"),
        ),
        migrations.AddField(
            model_name="banda",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="bandas_fotos/"),
        ),
        migrations.AddField(
            model_name="musica",
            name="letra",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="musica",
            name="spotify_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="musica",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
