# Generated by Django 5.1.3 on 2025-04-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "ano",
                    models.IntegerField(
                        choices=[(1, "1º Ano"), (2, "2º Ano"), (3, "3º Ano")]
                    ),
                ),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "1º Semestre"), (2, "2º Semestre")]
                    ),
                ),
                ("docentes", models.CharField(max_length=255)),
                ("link_moodle", models.URLField(blank=True, null=True)),
                ("link_ulusofona", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("logotipo", models.ImageField(upload_to="logos_tecnologias/")),
                ("link", models.URLField(blank=True, null=True)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("link_github", models.URLField(blank=True, null=True)),
                ("link_demo", models.URLField(blank=True, null=True)),
                ("conceitos_aplicados", models.TextField()),
                ("desafios_interessantes", models.TextField()),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.disciplina",
                    ),
                ),
                (
                    "tecnologias_utilizadas",
                    models.ManyToManyField(
                        related_name="projetos_associados", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_projetos/")),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
    ]
