# Generated by Django 5.1.3 on 2025-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_magiclinktoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclinktoken",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
