# Generated by Django 5.1.3 on 2025-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_magiclinktoken_used"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("dataInicio", models.DateTimeField(auto_now_add=True)),
                ("dataFim", models.DateTimeField(auto_now_add=True)),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="experiencias", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="experiencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
        ),
    ]
